---
- name: Download dbeaver
  get_url: url={{ dbeaver_url_deb }} dest={{dbeaver_tmp_deb}}
  tags: ["packages","dbeaver"]

- name: Install dbeaver for Debian OS family
  apt: deb={{dbeaver_tmp_deb}}
  tags: ["packages","dbeaver"]
